class date:
    def __init__(self,d,m,y,e,s):
        self.day=d
        self.month=m
        self.year=y
        self.events=e
        self.how_Saturdays=s
    def show_date(self):
        ...
    def display_week_in_date(self):
        ...
    def convert_solarDate_to_GeorgianDate(self):
        ...
    def convert_GregorianDate_to_SolarDate(self):
        ...    
    def convert_lunarDate_to_SolarDate(self):
        ...    
    def show_Calendar(self):
        ...
    def show_events_date(self):
        ...