class time:
    def __init__(self,h,m,s):
        self.hour=h
        self.minute=m
        self.second=s
    def hour_to_minute(self):
        ...
    def hour_to_second(self):
        ...
    def hour_to_minute(self):
        ...
    def second_to_hour(self):
        ...
    def day_to_second(self):
        ...
    def sum_to_time(self):
        ...    
    def sub_to_time(self):
        ... 